version: "3.8"
services:
  db:
    build: db/
    restart: unless-stopped
    volumes:
      - ./db/logs:/logs
      - ./db/data:/var/lib/neo4j/data
    ports:
      - 7474:7474
      - 7687:7687

  app:
    build: app/
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 5000:5000
    command: python3 ./app.py




